server:
  port: 9091
spring :
   application :
      name : userService
   zipkin:
     base-url: http://localhost:7777
     locator:
        discovery:
            enabled: true
   sleuth:
    sampler:
      probability: 1.0
    web:  
           skipPattern : (^cleanup.*)     
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
      
 